# Generated by Django 6.0.5 on 2026-06-20 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire (XAF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('create', 'Création'), ('delete', 'Suppression'), ('reset', 'Réinitialisation')], max_length=10)),
                ('qty', models.IntegerField(default=0)),
                ('before', models.IntegerField(default=0)),
                ('after', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.item')),
            ],
            options={
                'ordering': ['ts'],
            },
        ),
    ]
