# Generated by Django 6.0.5 on 2026-06-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True, verbose_name='Jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movements_count', models.IntegerField(default=0)),
                ('total_in', models.IntegerField(default=0)),
                ('total_out', models.IntegerField(default=0)),
                ('sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('content', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
    ]
