# Generated by Django 6.0.5 on 2026-06-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom'),
        ),
    ]
