# Generated by Django 6.0.5 on 2026-06-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_etab_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=120, verbose_name="Nom de l'établissement"),
        ),
    ]
